### ISSUE TITLE
Support for additional dev boards

### ISSUE THREAD

**Issue by ammaree** [sukesh-ak/LVGL8x-SDSPI-Template#1]
Can you please consider adding support for the following boards:

ESP-WROVER-KIT with 320x240 SPI without touch 
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/hw-reference/esp32/get-started-wrover-kit.html

Makerfabs ESP32-S3 with 480x320 parallel 3.5"
https://www.makerfabs.com/esp32-s3-parallel-tft-with-touch-ili9488.html

**Comment by sukesh-ak** [comment]
@ammaree 
For WROVER_KIT, create a file called `conf_wrover_kit.h` in the main folder and with below content. Then reference it in the main.cpp

LovyanGFX should autodetect the board LCD with this.

```c++
// filename 'conf_wrover_kit.h'

#define LGFX_ESP_WROVER_KIT        // ESP-WROVER-KIT

// Portrait
#define TFT_WIDTH   320
#define TFT_HEIGHT  240

#define TOUCH_ENABLED
#define SD_ENABLED

#include <LovyanGFX.h>
#include <LGFX_AUTODETECT.hpp>
```

Please keep in mind, I don't have these boards so its untested.
For SD card using shared SPI bus, you should check the file inside main folder called `helper_storage.hpp`

**Comment by ammaree** [comment]
@sukesh-ak 

Just remember the ESP-WROVER-KIT does not have any touch.

As far as SD is concerned have not used up to now, believe there might be hardware/pins conflict between LCD and SDcard?

**Comment by sukesh-ak** [comment]
> @sukesh-ak
> 
> Just remember the ESP-WROVER-KIT does not have any touch.
> 
> As far as SD is concerned have not used up to now, believe there might be hardware/pins conflict between LCD and SDcard?

SD card works with LCD with shared SPI using a different CS PIN for both.

You can see an example here.
https://github.com/sukesh-ak/ESP32-LVGL8x-SDSPI/blob/master/main/conf_FeatherS3_ILI9341.h

**Comment by sukesh-ak** [comment]
I worked with @lovyan03 to fix a bug related to shared SPI bus earlier. So it works.
https://github.com/lovyan03/LovyanGFX/issues/248

**Comment by sukesh-ak** [comment]
@ammaree 
I have added a request for Makerfabs ESP32-S3. 
https://github.com/lovyan03/LovyanGFX/issues/285

If this is done, it will be easy like above without much configuration.
Sorry, I don't have a device to try and test it.

You can manually configure looking at this sample
https://github.com/lovyan03/LovyanGFX/blob/master/examples/HowToUse/2_user_setting/2_user_setting.ino

Datasheet for the device is here
https://github.com/Makerfabs/Makerfabs-ESP32-S3-Parallel-TFT-with-Touch/blob/main/hardware/ESP32-S3%20Parallel%20TFT%20with%20Touch%20v1.0(3.5''%20ili9488).pdf

**Comment by ammaree** [comment]
Thanks
