### ISSUE TITLE
how to modify the setup in PlatformIO environment?

### ISSUE THREAD

**Issue by Pepito-design** [sukesh-ak/LVGL8x-SDSPI-Template#4]
Hi,
I'm working in VSC/PlatformIO environment on ESP32 S3.
LovyanGFX 1.1.12
lvgl 8.3.11
ILI9488  LCD 320x480
Touch_FT5x06 (I2C)
works fine. 
Now I'm trying to use the SD Card attached on the LCD module.
Shared with SPI of the LCD, SD_CS is separated to GPIO 47

cfg.bus_shared       =  true;    // shared SPI bus

But it's not possible to mount the SD ( 64GB,  FAT32 format )
#ifndef SDCARD_SS_PIN
#define SDCARD_SS_PIN 47   // CS für SD Karte
#endif

#ifndef SDCARD_SPI
#define SDCARD_SPI SPI
#endif

 setup()
  {
 ....
  ....
  pinMode(SDCARD_SS_PIN, OUTPUT);       // CS SD Karte
  digitalWrite(SDCARD_SS_PIN, HIGH);    // Inaktiv
  if ( ! SD.begin(SDCARD_SS_PIN, SDCARD_SPI, 25000000))    // 
   {
    Serial.println("Fehler: SD Card Mount fehlgeschlagen");
   }
  else
   {
.....
...

If I set 
#define LV_USE_FS_FATFS  1
the following error occurs:
Compiling .pio/build/esp32-s3-devkitc-1/lib7f8/lvgl/extra/widgets/animimg/lv_animimg.c.o
.pio/libdeps/esp32-s3-devkitc-1/lvgl/src/extra/libs/fsdrv/lv_fs_fatfs.c: In function 'fs_dir_open':
.pio/libdeps/esp32-s3-devkitc-1/lvgl/src/extra/libs/fsdrv/lv_fs_fatfs.c:228:5: error: unknown type name 'DIR'; did you mean 'DDR'?
     DIR * d = lv_mem_alloc(sizeof(DIR));
     ^~~
     DDR

At the moment, I didn't find any useful hint to solve that.
Was already thinking to use a second, separated SPI channel, but I need the GPIOs for other things ...
Thanks for any useful hint
Peter

**Comment by sukesh-ak** [comment]
This is an older project. 
Latest one is called `ESP32-TUX`
